model:
  name: 'hf/flan-t5-xl'
  type: 'seq2seqlm'  # Defaults to "CausalLM"
  class: ''  # If supplied, supersedes model.type

output:
  suffix: '-JDG-T-101'  # Suffix added to the name of the finetuned model. If empty, this will be the filename of the config file (without the yaml extension)

tokenizer:
  class: ''  # If supplied, uses this instead of AutoTokenizer
  add_pad_token: false  # If True, will add pad_token as the tokenizer's pad token
  pad_token: 'eos_token'  # "eos_token" will mean tokenizer.eos_token. Anything else will be taken literally.
  padding_side: 'right'  # Either "right" or "left"

dataset:
  # For now, only local datasets inside the "datasets" folder are used
  type: 'json'
  train: 'ReviewTags_v1_train.jsonl'
  eval: 'ReviewTags_v1_eval.jsonl'
  prompt_template: 'prompt_templates/review_tags_template.json'
  prompt_max_len: 512
  completion_max_len: 128 #For CausalLM, this is ignored
  # Future, not yet implemented:
  use_hf_datasets: false
  hf_dataset_name: ''
  hf_splits: []


from_pretrained:
  torch_dtype: 'bf16'  # Default: auto

lora:
  use_lora: true  # Set to True to create a LoRA or QLoRA adapter
  r: 8
  alpha: 32
  dropout: 0.05
  target_modules:
    - 'q'
    - 'v'
    - 'k'
    - 'o'
    - 'wi_0'
    - 'wi_1'
    - 'wo'
  # target_modules:
  #     - 'q_proj'
  #     - 'o_proj'
  #     - 'k_proj'
  #     - 'v_proj'
  #     - 'gate_proj'
  #     - 'up_proj'
  #     - 'down_proj'
  bias: 'none'
  task_type: 'CAUSAL_LM'

# Quantization Settings section
quant:
  quantize: true  # Set to True to train a quantized model (must use LoRA)
  load_in_4bit: true
  bnb_4bit_quant_type: 'nf4'
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: 'bf16'

# TrainingArguments section
train_args:
  num_epochs: 40  # Int > 0, must be specified.
  load_best_model_at_end: false  # Whether to load the best model at the end of training
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 1
  warmup_steps: 100
  save_steps: 100
  eval_steps: 10
  weight_decay: 0.5
  learning_rate: 0.0001
  logging_steps: 10
  gradient_checkpointing: true
  optim: 'adafactor'
  evaluation_strategy: 'steps'
  save_strategy: 'steps'
  logging_strategy: 'steps'
  log_level: 'warning'
  bf16: false
  fp16: false
